Calysto/metakernel

metakernel/_metakernel.py
There is a duplicate item ("_repr_html_", "text/html") in the list.
I think it would be better to remove it.
=> Removed duplicate ("_repr_html_", "text/html") item

metakernel/_metakernel.py
Hi, I've added some handling to support IPython 4 renaming issue. It should keep the old working but also add support for IPython 4. I am running now on IPython 4.
=> Support also for IPython 4 / jupyter

metakernel/pexpect.py
timeout=None was overwritten by self.timeout, however timeout=None is a valid timeout value which should be passed forward instead of resetting it
[I recognized this while using the new octave_kernel for jupyter. Out of sudden things broke with a timeout error. Now it works again as expected and I can use the jupyter notebook as normal.]
=> bug fixed timeout=None

metakernel/replwrap.py
I am not sure whether this is the right place to adapt, however it gives the desired result and prevents the timeout error message (printed below).
Maybe there are still more of such mistakes surrounding the timeout=-1 default.
```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 212, in dispatch_shell
handler(stream, idents, msg)
File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 370, in execute_request
user_expressions, allow_stdin)
File "/usr/local/lib/python2.7/dist-packages/metakernel/_metakernel.py", line 337, in do_execute
retval = self.do_execute_direct(code)
File "/usr/local/lib/python2.7/dist-packages/octave_kernel.py", line 88, in …
```
=> still timeout=None seems to be ignored

metakernel/magics/activity_magic.py
=> Fix import from ipywidgets

metakernel/process_metakernel.py, metakernel/tests/test_process_metakernel.py
removes the need for special `repr` method on this class, instead using a class designating text output that shouldn't get quotes added to it.
potential alternative to #87
closes Calysto/octave_kernel#30
=> wrap output in TextOutput in ProcessMetaKernel

metakernel/_metakernel.py
Sorry I broke everything...
While the previous implementation improved kernelspec installation, it
actually did not actually allow starting one.  This is because traitlets
assumes that class names start with an uppercase letter, so
`_MetaKernelApp` must be renamed to `MetaKernelApp`.  Fortunately it
still remains private as it is only defined in `metakernel._metakernel`.
(See https://github.com/ipython/ipython/pull/4276#issuecomment-26621822)
=> Fix kernelspec install.

metakernel/_metakernel.py, metakernel/config.py
=> Save history as JSON, to handle multiline entries.

metakernel/_metakernel.py
This line was added to workaround this bug:
https://github.com/ipython/ipykernel/pull/185/files#diff-cf792864a29c5f1f583e02552983ac09R70
Can now be removed.
=> Remove workaround

metakernel/parser.py
Allows kernels to override path escaping by overwriting
`self.parser.escape_path`.
See #107.
=> Expose path escaper.

metakernel/magic.py, metakernel/magics/plot_magic.py, metakernel/magics/tests/test_plot_magic.py
This changes the semantics somewhat for kernel authors in that the existing settings are replaced instead of updated and no default settings are applied other than backend.  However, this is more in line with what the user has requested. 
Fixes #102.
=> Clean up plot magic handling and add width/height options

metakernel/process_metakernel.py, metakernel/replwrap.py, metakernel/tests/test_replwrap.py
Tested using the `keyboard` command in Octave:
=> Add support for stdin requests and clean up replwrap

metakernel/__init__.py, metakernel/_metakernel.py, metakernel/magics/python_magic.py, metakernel/magics/tests/test_python_magic.py
This is a rough draft for being able to better support ipython style exception handling instead of just printing to stderr. 
This will also allow us to make tools like nbconvert happier since we can actually fail now -- previously all messages would always be of status 'ok'.
Let me know if you want anything else in here.  
I'm currently working on a scala metakernal in https://github.com/mariusvniekerk/spylon-kernel
=> Added support for better error handling to metakernel

metakernel/replwrap.py
`pexpect` uses `crlf` for incoming and `linesep` for outgoing.
=> Use clrf for end of line response from process

.travis.yml, metakernel/magics/python_magic.py
This is sort-of a revert of #129, or a bit of a remix. It should fix #136.
Both Fedora and Ubuntu seem to be on 0.9, so I think it makes sense to keep compatibility rather than bumping the requirements.
=> Restore Jedi 0.9 compatibility

metakernel/magics/tests/test_download_magic.py, metakernel/magics/tests/test_install_magic_magic.py, metakernel/magics/tests/test_jigsaw_magic.py
This enables builders on network-constrained systems to avoid those tests.
Also fix an error in the tear down of `test_install_magic_magic` if it fails.
=> Mark tests that use the network

metakernel_bash/setup.py, metakernel_echo/setup.py, metakernel_python/setup.py
This just resyncs them with the main `metakernel` package. I'm fairly certain these have all been changed since 0.11.3 at least a little bit.
=> Update versions of MetaKernel kernels.

metakernel/_metakernel.py
I was attempting to add images to the Octave kernel and prior to this change the metakernel images were getting picked up because `__name__` was `metakernel._metakernel` in this context.   Also verified with https://github.com/Calysto/calysto_prolog that this change makes it pick up the correct images.
=> Get kernel images from package if possible

metakernel/_metakernel.py, metakernel/magics/python_magic.py
We are getting `IOError` in Ubuntu instead of `OSError`.  cf https://github.com/Calysto/matlab_kernel/issues/102
=> Fix handling of fallback images

metakernel/replwrap.py
This is related to https://github.com/Calysto/scilab_kernel/issues/3#issuecomment-338438696.  We need to pass a list because `shlex.split` doesn't work with Windows paths.
=> Allow a list to be passed as the command

metakernel/pexpect.py, metakernel/replwrap.py
- Only accept strings for commands, and no args
- Only send one line at a time for a command if there is no command emit prompt
=> Replwrap fixes

metakernel_bash/metakernel_bash.py, metakernel_echo/metakernel_echo.py
Use sys.executable when creating kernel.json for echo and bash. This is already the case for python.
=> Use sys.executable when creating kernel.json

metakernel/tests/test_replwrap.py
The test_python test relies on finding an executable called "python" in the path. The symlink from python to python2 is not guaranteed to exist. And when it is not present the test fails as follows:
````
test_python (metakernel.tests.test_replwrap.REPLWrapTestCase) ... ERROR
======================================================================
ERROR: test_python (metakernel.tests.test_replwrap.REPLWrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/builddir/build/BUILD/metakernel-0.20.14/metakernel/tests/test_replwrap.py", line 62, in test_python
p = replwrap.python()
File "/builddir/build/BUILD/metakernel-0.20.14/metakernel/replwrap.py", line 214, in python
u("import sys; sys.ps1={0!r}; sys.ps2={1!r}"))
File …
```
=> Don't rely on 'python' in path during testing

metakernel/_metakernel.py, metakernel/magic.py
We're building an `ipdb` kernel for Spyder with MetaKernel. For that we defined Pdb commands as magics and some of their names collide with MetaKernel default magics.
With this PR users could create magics that are loaded instead of MetaKernel ones with the same name.
=> Allow to redefine default MetaKernel magics with custom ones

.travis.yml, metakernel/_metakernel.py
@dsblank, @blink1073, we need to maintain Python 2 compatibility in Spyder until Python 2 end of life, so we would need MetaKernel to work with Python 2 until that date too.
To not add to you more work than you should be doing, we're willing to offer our time to keep maintaining Python 2 until that date.
Hope you're ok with that.
=> Fix for Python 2 compatibility

metakernel/_metakernel.py
We're using `Image` objects from `IPython.core.display` to create a simple inline backend for Matplotlib in our kernel, and we're passing them some metadata.
This case was handled incorrectly by Metakernel because `repr_png/jpeg` of `Image`'s is a tuple of the form `(data, metadata)` instead of a single string.
=> Fix handling metadata in _formatter

metakernel/replwrap.py
cf https://github.com/Calysto/octave_kernel/issues/129
=> Avoid double printing output in process kernels

metakernel/magics/shell_magic.py, metakernel/replwrap.py
This is in line with the default behavior of the notebook when launching terminals (as well as VS Code).
=> Switch to powershell on windows

README.rst, metakernel/_metakernel.py
Make it easier for subclasses to provide configurability and update docs.
=> Clean up configurability handling and docs

LICENSE.txt
The terms of the BSD license require all copies of the code include the text of the license.
=> Add the full license

metakernel/_metakernel.py
````
>   objects = [i for i in objects if not isinstance(i, Widget)]
E   TypeError: isinstance() arg 2 must be a type or tuple of types
````
=> Fix TypeError

metakernel/_metakernel.py
This fixes #207 ipywidget display as well as ROOT-10971 for the ROOT kernel.
The protocol for displaying ipywidgets seems to have changed and simply
passing the mime bundle to ipython does not work.
=> fix ipywidgets display

metakernel/_metakernel.py, metakernel/magics/python_magic.py
This fixes python evals so that the code matches the comments.  Without
the patch the non-retval version of python eval will not work.
=> fix python evals #208

metakernel/tests/test_metakernel.py
The Debian [autopkgtest command ](https://salsa.debian.org/ci-team/autopkgtest/-/blob/master/doc/README.package-tests.rst) runs by default in an environment where the current working directory is not writeable. So, instead, use a proper tempfile to test the %ls magic.
=> use tempfile instead of writing to cwd

metakernel/replwrap.py, metakernel/tests/test_replwrap.py
Bash 5.1 enables bracketed paste mode by default when it detects that it
is connected to a [pt]ty. This causes extra terminal escape codes to be
emitted in the output, confusing pexpect. Setting TERM=dumb disables
this, allowing the bash REPLWrapper to function correctly.
=> use TERM=dumb for bash REPLWrapper

docs/conf.py
As part of the Reproducible Builds effort [0] it was noticed that metakernel could not be built reproducibly due to the build year embedded in the documentation. The recommended approach is to use SOURCE_DATE_EPOCH [1].
[0] https://reproducible-builds.org/
[1] https://reproducible-builds.org/specs/source-date-epoch/
=> add support for SOURCE_DATE_EPOCH

metakernel/magics/python_magic.py
Compilation fails on e.g. Fedora 32:
```
>       completions = interpreter.complete()
E       AttributeError: 'Interpreter' object has no attribute 'complete'
```
=> Support older jedi versions

metakernel/magics/README.md, metakernel/magics/latex_magic.py, metakernel/magics/tests/test_latex_magic.py
The %latex and %%latex magics need dollar signs around equations. See the screen dump:
This PR also addresses the warnings:
```
metakernel/magics/tests/test_latex_magic.py:8
/builddir/build/BUILD/metakernel-0.27.3/metakernel/magics/tests/test_latex_magic.py:8: DeprecationWarning: invalid escape sequence \d
kernel.do_execute("%latex x_1 = \dfrace{a}{b}")
metakernel/magics/tests/test_latex_magic.py:14
/builddir/build/BUILD/metakernel-0.27.3/metakernel/magics/tests/test_latex_magic.py:14: DeprecationWarning: invalid escape sequence \d
kernel.do_execute("""%%latex
```
=> Add missing dollar signs to %latex examples and tests

metakernel/tests/test_parser.py
Addresses these warnings:
```
metakernel/tests/test_parser.py:74
/builddir/build/BUILD/metakernel-0.27.3/metakernel/tests/test_parser.py:74: DeprecationWarning: invalid escape sequence \ 
assert "Test\ Dir/" in info['path_matches'], info['path_matches']
metakernel/tests/test_parser.py:104
/builddir/build/BUILD/metakernel-0.27.3/metakernel/tests/test_parser.py:104: DeprecationWarning: invalid escape sequence \ 
assert "Test\ Dir/" in info['path_matches'], info['path_matches']
metakernel/tests/test_parser.py:116
/builddir/build/BUILD/metakernel-0.27.3/metakernel/tests/test_parser.py:116: DeprecationWarning: invalid escape sequence \ 
assert 'Test\ Dir/' in info['path_matches'], info
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```
=> Escape backslashes in strings

metakernel/magics/blockly_magic.py
There are many problems in the jigsaw_magic module. 
For example, the CORS problem caused by IFrame， jigsaw_magic use code
```javascript
cell.element[0].children[2].children[1].children[2].children[1].children[0].innerHTML = ""
```
A blockly module is added to solve these problems
=> Add a blockly magic instead of a jigsaw magic

CHANGELOG.md
Automated Changelog Entry for 0.28.0 on master
| Branch  | master  |
| Version Spec | 0.28.0 |
| Since | 0.27.5 |
=> Automated Changelog Entry for 0.28.0 on master

setup.cfg
This prevented the release of 0.28.0.
=> Fix trove classifier

CHANGELOG.md
Automated Changelog Entry for 0.28.1 on master
| Branch  | master  |
| Version Spec | 0.28.1 |
| Since | v0.28.0 |
=> Automated Changelog Entry for 0.28.1 on master

CHANGELOG.md
Automated Changelog Entry for 0.28.2 on master
| Branch  | master  |
| Version Spec | 0.28.2 |
| Since | v0.28.1 |
=> Automated Changelog Entry for 0.28.2 on master

metakernel/tests/test_expect.py, pyproject.toml
metakernel/tests/test_expect.py:113: in <module>
suite = unittest.makeSuite(ExpectTestCase, 'test')
/usr/lib64/python3.11/unittest/loader.py:491: in makeSuite
warnings.warn(
E   DeprecationWarning: unittest.makeSuite() is deprecated and will be removed in Python 3.13. Please use unittest.TestLoader.loadTestsFromTestCase() instead.
~~~
metakernel/__init__.py:1: in <module>
from ._metakernel import (
metakernel/_metakernel.py:22: in <module>
from ipykernel.kernelapp import IPKernelApp
/usr/lib/python3.10/site-packages/ipykernel/kernelapp.py:42: in <module>
from .ipkernel import IPythonKernel
/usr/lib/python3.10/site-packages/ipykernel/ipkernel.py:19: in <module>
from .eventloops import _use_appnope
/usr/lib/python3.10/site-packages/ipykernel/eventloops.py:13: in <module>
from …
=> Address deprecation warnings

metakernel/replwrap.py, metakernel/tests/test_replwrap.py
This fixes downstream https://github.com/blink1073/oct2py/issues/237 and https://github.com/blink1073/oct2py/issues/248 as well as addressing the cause behind #228 .
The rationale is complicated somewhat by the fact that python [disabled](https://bugs.python.org/issue42819) bracketed paste mode soon after #228, so that test doesn't fail anymore. I added a test that *would* fail without stripping the bracketing, by explicitly enabling it.
I think this is still the right place for this code (rather than downstream), since the readline default is to include the control characters, so I expect that stripping them will be common across multiple REPLs (including some `bash` invocations).
=> Strip paste-bracketing control characters

CHANGELOG.md
Automated Changelog Entry for 0.29.1 on main
| Branch  | main  |
| Version Spec | next |
| Since | v0.29.0 |
=> Automated Changelog Entry for 0.29.1 on main

metakernel_echo/metakernel_echo.py, metakernel_python/metakernel_python.py
When the build system was updated the version information for
metakernel-echo and metakernel-python was lost and the versions
changed from 0.19.1 to 0.1.0. In order for the versions not to go
backwards on update this commit resets them to their previous values.
=> Restore versions of metakernel-echo and metakernel-python

CHANGELOG.md
Automated Changelog Entry for 0.29.2 on main
| Branch  | main  |
| Version Spec | next |
| Since | v0.29.1 |
=> Automated Changelog Entry for 0.29.2 on main

metakernel/magics/tests/test_parallel_magic.py, pyproject.toml
The pytest configuration was recently changed from running tests in all directories except from a list of exclusions to running test only in a set of listed directories. In this change the magics tests in metakernel/magics/tests were lost. This PR puts them back.
Without the change:
============================= 40 passed in 23.08s ==============================
With the change:
======================== 79 passed, 3 skipped in 38.40s ========================
=> Add back magics tests

README.rst
Clicking this link with `ipython` as the nbviewer host leads to redirects that don't resolve. Switching to jupyter fixes this.
=> Change nbviewer URL to use Jupyter

pyproject.toml
It is deprecated in Python 3.12.
The call that causes the warning is in jupyter_client. This causes 56 tests to fail. First failure is:
~~~
_______________________________ test_get_magics ________________________________
def test_get_magics():
>       kernel = get_kernel()
/builddir/build/BUILD/metakernel-0.29.4/metakernel/tests/test_magic.py:35: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ /builddir/build/BUILD/metakernel-0.29.4/metakernel/tests/utils.py:84: in get_kernel
kernel = kernel_class(session=ss.Session(), iopub_socket=iopub_socket,
/usr/lib/python3.12/site-packages/jupyter_client/session.py:568: in __init__
self._check_packers()
/usr/lib/python3.12/site-packages/jupyter_client/session.py:634: in _check_packers
msg_datetime = dict(t=utcnow())
_ …
=> Ignore DeprecationWarnings for datetime.utcnow()

metakernel/parser.py
This PR fixes an edge case in magic completions:
Currently:
If you press TAB after `%` or `%%` and select an item it doubles the percents
Example:
%&lt;TAB> and select, say, `%cd` you'll get `%%cd`
After PR:
If you press TAB after `%` or `%%` and select an item it properly gives selection
Example:
%&lt;TAB> and select, say, `%cd` you'll get `%cd`
=> Fix magic completion

.github/workflows/tests.yml, docs/requirements.txt, metakernel/__init__.py, metakernel/magics/dot_magic.py, metakernel/magics/tests/test_dot_magic.py
This PR:
* updates the dot magic to work with current pydot
* adds tests for dot magics (cell and line)
* updates version
=> Updated dot magic, with tests

pyproject.toml
The error message changed from "datetime.utcnow() is deprecated" to "datetime.datetime.utcnow() is deprecated".
=> Adapt to Python 3.12.0rc2

.github/dependabot.yml, .github/workflows/tests.yml, metakernel/magics/tests/test_parallel_magic.py, pyproject.toml
- Skip parallel tests on MacOS, since they have been failing
- Update supported Pythons to 3.8-3.12
- Update dependabot config
=> Clean up CI

README.rst
Apparently something about .rst rendering changed in GitHub which requires a space between `code::` and the syntax to use now. Without the space it simply doesn't render which is quite confusing:
With the fix in this PR:
=> Fix installation code blocks in readme

.github/workflows/tests.yml, README.rst, metakernel/tests/test_magic.py, pyproject.toml
Support Python 3.9-3.13
Remove dead link to coveralls.
=> Update supported Pythons and fix links
