- .travis.yml
Test against Jupyter v4 on 2.7 and 3.4, but also test v3 on 3.3.
> Jupyter 4 test

- metakernel/magics/shell_magic.py
- metakernel/process_metakernel.py
- metakernel/replwrap.py
Fixes #79, from MetaKernel Bash:
> Allow long running tasks to print

- metakernel/magics/shell_magic.py
I was digging around and noticed this if statement was not needed.
> Remove redundant if statement.

- metakernel/pexpect.py
- metakernel/replwrap.py
> Improvements to bash handling from bash_kernel

- .coveragerc
- metakernel/process_metakernel.py
- metakernel/replwrap.py
Clean up of keyboard interrupt and shutdown behavior on Posix and Windows.
Verified with https://github.com/Calysto/octave_kernel/pull/63.
> Replwrap cleanup

- metakernel/_metakernel.py
- metakernel/magics/kernel_magic.py
Fixes https://github.com/Calysto/matlab_kernel/issues/60
> Clean up kernel magic

- .travis.yml
- metakernel/magics/python_magic.py
> Update for jedi 0.10

- metakernel/magics/help_magic.py
- metakernel/magics/python_magic.py
> Make help logic more robust

- metakernel/magics/shell_magic.py
- metakernel/replwrap.py
cf https://github.com/Calysto/matlab_kernel/issues/88#issuecomment-285889345.
> Remove shell ambiguity

- metakernel/replwrap.py
Fix for #140 
This seems to solve the issue and match with what you were saying in the issue, let me know if anything needs to change or be added.
> adding call to close on child pty

- metakernel/pexpect.py
- metakernel/replwrap.py
Improvement on #154.  The previous version didn't work on posix systems...
> Clean up handling of command and args

- metakernel/replwrap.py
- metakernel/tests/test_process_metakernel.py
cf https://github.com/Calysto/octave_kernel/issues/144
> Carriage Return Handling for ProcessKernel

- Makefile
- metakernel/magics/activity_magic.py
- metakernel/magics/parallel_magic.py
- setup.py
> portalocker and ipyparallel as optional dependencies

- metakernel/replwrap.py
As proposed by @blink1073 in https://github.com/Calysto/metakernel/issues/203#issuecomment-611507527_
> Remove undefined line in expect stdin #203

- .travis.yml
- metakernel/_metakernel.py
- metakernel/magic.py
- metakernel/magics/jigsaw_magic.py
- metakernel/magics/tests/test_shell_magic.py
> fix warnings

- .travis.yml
- setup.py
> More py2 removal

- metakernel/magics/jigsaw_magic.py
Fix #230 IPython Iframe display not working;
Pass html filename only to IFrame, and add missing width and height
> Fix Iframe display issue

- pyproject.toml
> Switch to hatch backend

- .github/dependabot.yml
- .github/workflows/check-release.yml
- .github/workflows/tests.yml
- Makefile
- conftest.py
- metakernel/tests/conftest.py
- pyproject.toml
- Add dependabot config
- Clean up actions and switch to releaser v2
- Clean up handling of warnings
- Use new recommended env variable from `jupyter_core` 5.0
> Maintenance cleanup

- pyproject.toml
> Pin upper version of ipykernel

- .github/workflows/prep-release.yml
- .github/workflows/publish-changelog.yml
- .github/workflows/publish-release.yml
See https://github.com/jupyter-server/jupyter_releaser/pull/557 for context.
> Add Release Workflows

- metakernel/_metakernel.py
This class was removed in IPython 9.  Reported as https://github.com/blink1073/oct2py/issues/337
> Add ipython 9 compat
